# Generated by Django 4.2.7 on 2023-12-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Error_log', '0002_userprofile_delete_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('error_count', models.IntegerField(default=0)),
                ('threat_level', models.CharField(blank=True, max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
